"""add is_verified to users

Revision ID: 581a54994442
Revises: 26c7f4fb0482
Create Date: 2026-07-19 02:29:03.719175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581a54994442'
down_revision = '26c7f4fb0482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False,server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
